// Generated by CoffeeScript 1.6.3
module.exports = function(grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    sass: {
      build: {
        options: {
          style: "compressed"
        },
        expand: true,
        cwd: "app/sass/",
        src: ["styles.scss"],
        dest: "app/contents/css/",
        ext: ".css"
      },
      preview: {
        options: {
          style: "expanded",
          debugInfo: true,
          lineNumbers: true
        },
        expand: true,
        cwd: "app/sass/",
        src: ["styles.scss"],
        dest: "app/contents/css/",
        ext: ".css"
      }
    },
    coffee: {
      join: {
        options: {
          join: true
        },
        files: {
          "app/contents/js/main.js": ["app/coffee/*.coffee"]
        }
      }
    },
    cssmin: {
      normalize: {
        src: "app/bower_components/normalize-css/normalize.css",
        dest: "app/contents/css/normalize.min.css"
      }
    },
    concat: {
      options: {
        separator: ";"
      },
      libs: {
        src: ["app/bower_components/jquery/jquery.min.js"],
        dest: "app/contents/js/libs.js"
      }
    },
    watch: {
      build: {
        files: ["**/*.scss"],
        tasks: ["sass:build"],
        options: {
          spawn: false
        }
      },
      preview: {
        files: ["**/*.scss"],
        tasks: ["sass:preview"],
        options: {
          spawn: false
        }
      }
    },
    wintersmith: {
      build: {
        options: {
          action: "build",
          config: "app/config-build.json"
        }
      },
      preview: {
        options: {
          action: "preview",
          config: "app/config-preview.json"
        }
      }
    }
  });
  grunt.loadNpmTasks("grunt-contrib-sass");
  grunt.loadNpmTasks("grunt-contrib-coffee");
  grunt.loadNpmTasks("grunt-css");
  grunt.loadNpmTasks("grunt-contrib-concat");
  grunt.loadNpmTasks("grunt-contrib-watch");
  grunt.loadNpmTasks("grunt-wintersmith");
  grunt.registerTask("preview", ["wintersmith:preview", "watch:preview", "coffee:join"]);
  return grunt.registerTask("build", ["cssmin", "concat", "sass:build", "coffee:join", "wintersmith:build"]);
};
