// Generated by CoffeeScript 1.6.3
module.exports = function(grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    sass: {
      prod: {
        options: {
          style: "compressed"
        },
        expand: true,
        cwd: "app/sass/",
        src: ["styles.scss"],
        dest: "app/contents/css/",
        ext: ".css"
      },
      dev: {
        options: {
          style: "expanded",
          debugInfo: true,
          lineNumbers: true
        },
        expand: true,
        cwd: "app/sass/",
        src: ["styles.scss"],
        dest: "app/contents/css/",
        ext: ".css"
      }
    },
    coffee: {
      compile: {
        files: {
          'app/contents/js/test.js': 'app/coffee/test.coffee',
          'app/contents/js/test2.js': ['app/coffee/*.coffee']
        }
      },
      join: {
        options: {
          join: true
        },
        files: {
          "app/contents/js/test.js": "app/coffee/test.coffee",
          "app/contents/js/application.js": ["app/coffee/*.coffee"]
        }
      }
    },
    concat: {
      options: {
        separator: ";"
      },
      prod: {
        src: ["app/bower_components/jquery/jquery.min.js"],
        dest: "app/contents/js/library.js"
      }
    },
    watch: {
      prod: {
        files: ["**/*.scss"],
        tasks: ["sass:prod"],
        options: {
          spawn: false
        }
      },
      dev: {
        files: ["**/*.scss"],
        tasks: ["sass:dev"],
        options: {
          spawn: false
        }
      }
    },
    wintersmith: {
      prod: {
        options: {
          action: "build",
          config: "app/config-prod.json"
        }
      },
      dev: {
        options: {
          action: "preview",
          config: "app/config-dev.json"
        }
      }
    }
  });
  grunt.loadNpmTasks("grunt-contrib-sass");
  grunt.loadNpmTasks("grunt-contrib-coffee");
  grunt.loadNpmTasks("grunt-contrib-concat");
  grunt.loadNpmTasks("grunt-contrib-watch");
  grunt.loadNpmTasks("grunt-wintersmith");
  grunt.registerTask("preview", ["watch:dev", "coffee:join", "wintersmith:dev"]);
  return grunt.registerTask("prod", ["sass:prod", "coffee:join", "wintersmith:prod"]);
};
