// Generated by CoffeeScript 1.6.3
(function($) {
  return $.fn.highlight = function() {
    $(this).css({
      color: "red",
      background: "yellow",
      padding: "1em"
    });
    return $(this).fadeIn();
  };
})(jQuery);
